version: 2
build:
  image: latest
python:
  version: 3
  install:
    - requirements: docs/requirements.txt
    - method: pip
  system_packages: true
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
formats:
  - epub
  - pdf
